### PR TITLE
bug fixes

### PR DESCRIPTION
**Pull request by pboley**
Fix loading OIFITS files with a single wavelength entry

### CODE REVIEW

**Review by amerand — APPROVED** [review]

**Review by amerand — COMMENTED** [review]
Can you tell me what this does exactly?

**Review by amerand — APPROVED** [review]
Thanks for catching this!

**Comment by pboley** [comment]
> I am not familiar with this syntax... I thought the code worked using single-wavelength data! can you tell me which data set caused this issue (if you agree to share the OIFITS with me)

This insures that the numpy array is 2d. For multi-wavelength data, which here are already 2d arrays, it does nothing. The length along the first axis is the number of elements selected by "True" in w (=w.sum()), and the number of elements along the second axis is inferred automatically (see [reshape documentation](https://numpy.org/doc/stable/reference/generated/numpy.reshape.html)). For single-wavelength data, this was breaking. I'll send a sample file by email in a few minutes.

**Review by amerand — APPROVED** [review]

**Review by amerand — APPROVED** [review]

**Review by amerand — APPROVED** [review]

**Comment by amerand** [comment]
I commited all corrections, thanks!

**Pull request closed without merging**
